project:
  type: book

book:
  title: "De kwaliteit van grootschalige ‘performance assessments’ gewikt en gewogen"
  author: "Alexia Deneire, Jetje De Groof, Liesje Coertjens, Vincent Donche, Jan Vanhoof, Peter Van Petegem, Sven De Maeyer"
  date: "03/01/2022"
  sidebar:
    style: docked
    background: light
  logo: edubron-nl-rgb.jpg
  page-footer: 
    left: "Copyright 2022, EduBROn, www.edubron.be"
  chapters:
    - index.qmd
    - intro.qmd
    - probleemstelling.qmd
    - Ontwikkeling_matrix.qmd
    - buitenlandse_voorbeelden.qmd
    - evaluatiematrix.qmd
    - uitdagingen.qmd
    - implicaties.qmd
    - woordenlijst.qmd
    - references.qmd
  downloads: [pdf]
  sharing: [twitter, facebook]
language: dutch.yml
cls: apa6.cls
bibliography: references.bib

format:
  html:
    theme: cosmo
