# Voorwoord {.unnumbered}

Deze website is de online versie van het boek **"De kwaliteit van grootschalige ‘performance assessments’ gewikt en gewogen"**. 

Met dit boek willen we de inzichten verworven doorheen het project en vertaald in het rapport @demaeyerHoe2016 beschikbaar maken voor een breder publiek. Het meten van competenties is geen eenvoudige taak en dit grootschaliger uitrollen brengt een hele reeks van keuzes en uitdagingen met zich mee. Door dit boek open en vrij aan te bieden is het onze hoop dat we verschillende belanghebbenden kunnen bereiken en inspireren. 


::: {.callout-note appearance="simple"}
Het boek is gepubliceerd via [Quarto](https://quarto.org). Naast de online versie kan je tevens een gecompileerde pdf-versie downloaden: [download pdf](De-kwaliteit-van-grootschalige-‘performance-assessments’-gewikt-en-gewogen.pdf).
:::

## Licentie

Deze website is (en zal altijd) **vrij voor gebruik** zijn, en valt onder de [Creative Commons Attribution-NonCommercial-NoDerivs 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) Licentie.


Verwijzen naar het boek kan via volgende referentie:

Deneire, A., De Groof, J., Coertjens, L., Donche, V., Vanhoof, J., Van Petegem, P. en De Maeyer S. (2022). *"De kwaliteit van grootschalige ‘performance assessments’ gewikt en gewogen"*. Antwerpen: Edubron. url: [edubron-bookpa2022.netlify.app/](https://edubron-bookpa2022.netlify.app/)
